# Generated by Django 4.0.5 on 2022-06-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('segmento', models.CharField(max_length=30)),
                ('cantidadDeCilindros', models.IntegerField()),
                ('cilindrada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Camioneta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('cantidadDeCilindros', models.IntegerField()),
                ('cilindrada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('cantidadDeCilindros', models.IntegerField()),
                ('cilindrada', models.IntegerField()),
            ],
        ),
    ]
