# Generated by Django 4.0.5 on 2022-06-29 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='marca',
            new_name='fabricante',
        ),
        migrations.RenameField(
            model_name='camioneta',
            old_name='marca',
            new_name='fabricante',
        ),
        migrations.RenameField(
            model_name='moto',
            old_name='marca',
            new_name='fabricante',
        ),
    ]
